Create .gitignore
derek-repka/tictactoe pull request #1
Opened 2019-01-14 18:18 UTC by ZhimaoLin

Create .gitignore for the convenience during development.

2019-01-22 22:53 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        System.out.println("----------Scoreboard----------");
Recommended change: 
The header and footer of the scoreboard could be lengthened so they are centered.

Current: 
----------Scoreboard----------
Player O: 	win:0	lose:1	tie:0
Player X: 	win:1	lose:0	tie:0
------------------------------

Suggested:
------------Scoreboard--------------
Player O: 	win:0	lose:1	tie:0
Player X: 	win:1	lose:0	tie:0
---------------------------------------

2019-01-22 22:54 UTC, derek-repka requested changes

2019-01-22 22:54 UTC, derek-repka commented on pom.xml
> +
[Required] Some team members have had issues compiling the project, since the Maven compiler source and target are not set. As well, some warnings come up during compilations as the build source encoding is not set. Please add these to the properties tag.

2019-01-22 22:54 UTC, derek-repka commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                playAgain = keyboardScanner.nextLine();
[Desired] There are multiple places where you are doing multiple comparisons for upper and lowercase versions of inputted character for playing again. Instead, the code would be easier to read if the input was changed to lower case before doing any comparisons, so you don't need to check for uppercase responses.

2019-01-22 23:04 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        String playAgain = "y";
Recommended change:
I would expect a variable with the name "playAgain" to be a Boolean (so we could do something like "if(playAgain)").  As the variable's main purpose is to store user input, I would recommend renaming it for improved readability.

2019-01-22 23:04 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                System.out.println("play again: " + playAgain);
Is this a debug statement that you forgot to delete?  If it's meant to be there, that's fine.  I'm just pointing it out so you can delete it if that was the intention.

2019-01-22 23:20 UTC, Z-Red commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +            scoreboard[0][2] += 1;
[Desired] ```scoreboard[0][2]``` is somewhat ambiguous and it is not immediately clear what values are being tallied. Consider adding constant values for scoreboard win/loss types to improve readability and clarity within the code. 

```suggestion
            scoreboard[0][TIE] += 1;
```

2019-01-23 21:26 UTC, pshn111 commented on pom.xml
> +
We can run it on the lab machine without any warning.
Here is the INFO.
[INFO] Building jar: /cshome/spei/Desktop/402 test/tictactoe/target/TicTacToe-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.021 s
[INFO] Finished at: 2019-01-23T14:22:16-07:00
[INFO] Final Memory: 19M/142M
[INFO] ------------------------------------------------------------------------

2019-01-23 21:27 UTC, ZhimaoLin commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        System.out.println("----------Scoreboard----------");
Fixed.

2019-01-23 21:27 UTC, ZhimaoLin commented on pom.xml
> +
Won't fix.

2019-01-23 21:31 UTC, ZhimaoLin commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        String playAgain = "y";
We want to use variable playAgain to contain user input. Since users cannot input booleans, we decide to leave it for now. 
Won't fix.

2019-01-23 21:32 UTC, ZhimaoLin commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                playAgain = keyboardScanner.nextLine();
Fixed.

2019-01-23 21:35 UTC, ZhimaoLin commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                System.out.println("play again: " + playAgain);
Fixed.

2019-01-23 21:42 UTC, ZhimaoLin commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +            scoreboard[0][2] += 1;
Fixed by adding more comments.

2019-01-23 21:54 UTC, ZhimaoLin commented
We have addressed some of the comments that required changes. Please approve this pull request. Thanks.

2019-01-23 23:30 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                playAgain = keyboardScanner.nextLine();
Excellent, thank you.

2019-01-23 23:31 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        System.out.println("----------Scoreboard----------");
Excellent, thank you.

2019-01-23 23:32 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +        String playAgain = "y";
My suggestion was to rename the variable.  But this is just a suggestion, so we can accept the pull request without this change.

2019-01-23 23:32 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +                System.out.println("play again: " + playAgain);
Great, thank you.

2019-01-23 23:55 UTC, corey1994 commented on pom.xml
> +
Please add the following code, which will both allow compilation on machines with a newer Java version (Java 10) and as well as avoiding the warnings that Derek mentioned.  Our project, which includes these lines, still compiles on the lab machines as well.

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>
    </properties>

2019-01-24 01:53 UTC, corey1994 commented on src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
> +            scoreboard[0][2] += 1;
Great, thanks.

2019-01-24 01:53 UTC, corey1994 commented
Thank you for making those changes.

2019-01-24 01:59 UTC, ZhimaoLin commented on pom.xml
> +
Fixed.

2019-01-24 02:02 UTC, derek-repka commented on pom.xml
> +
Great, thanks!

2019-01-24 02:02 UTC, derek-repka approved these changes

2019-01-24 02:04 UTC, merged